// Define UI bindings
const form = document.querySelector('#db-task-from');
const taskList = document.querySelector('.collection');
const clearBtn = document.querySelector('.db-clear-tasks');
const filter = document.querySelector('#db-filter');
const taskInput = document.querySelector('#db-task');

// Order of function Expression does NOT matter. It's important to define them beffore call the first one.
// Later we should explorer how does it influence on performance
// But for now I follow the pricipe - the simplier is the better, so I Declare functions

// Load all event listeners
// Function  **Declarations** hoist the function definitions.
// NOTE: Function **Expressions** in JavaScript are NOT hoisted.
// Therefore, you **canNOT** use function expressions before defining them.

loadEventListeners();

// Define loadEventlisteners func

function loadEventListeners() {
  // Add task events

  form.addEventListener('submit', addTask);

  // Remove task events

  taskList.addEventListener('click', removeTask);
}

// Define addTask func

function addTask(e) {
  if (taskInput.value === '') {
    alert('Add a Task');
  }

  // Create li element

  const li = document.createElement('li');

  // Add a class

  li.className = 'collection-item';

  //  Create text node and append to li

  li.appendChild(document.createTextNode(taskInput.value));
  /* Cancel creating link element and just create an icon element
  // Create new link element

  // const link = document.createElement('a');

  // Add a class to link

  // link.className = 'db-delete-item secondary-content';
  */

  // Add icon html

  //  Here is icon from code awesome implmented by Brad

  // link.innerHTML = '<i class="fas fa-times read-text"></i>';

  // Here is I use standard materialaize icons
  // link.innerHTML =
  //   '<i class="material-icons red-text">remove_circle_outline</i>';

  // Alternative way to make an icon

  // Create icon

  const iconRemove = document.createElement('i');

  // Add a class to iconRemove

  iconRemove.className =
    'material-icons red-text db-delete-item secondary-content';

  // Add textNode to iconRemove

  iconRemove.appendChild(document.createTextNode('remove_circle_outline'));
  /*
  // Append icon to li as a child

  // link.appendChild(iconRemove);

  // Append link to li

  // li.appendChild(link);
  */

  li.appendChild(iconRemove);

  // Append li to ul as a child

  taskList.appendChild(li);

  // Clear inputTask

  taskInput.value = '';

  // Prevent default form action

  e.preventDefault();

  // Dev only

  // console.log(iconRemove);
  // console.log(link);
  // console.log(li);

  /**
   * JSDocs comments generated by VSCode
   */
}

function removeTask(e) {
  if (e.target.classList.contains('db-delete-item')) {
    console.log(e.target);
  }
}
